### ISSUE TITLE
virtualenv deprecated. see LCT or teammates' notes EOM

### ISSUE THREAD

**Issue by tofr** [PGreatness/import-Greatness#2]

**Comment by PGreatness** [comment]
As far as I can tell, `virtualenv` is still working and has not been selected for deprecation. As of Python version 3.6, the notes on [deprecated features for venv](https://docs.python.org/dev/whatsnew/3.6.html#id8) list `pyvenv` only. It has been done to avoid confusion with what it is tied to. 
The section on `venv` only mentions the following:

>Deprecated since version 3.6: `pyvenv` was the recommended tool for creating virtual environments for Python 3.3 and 3.4, and [is deprecated in Python 3.6](https://docs.python.org/dev/whatsnew/3.6.html#deprecated-features).

This, I believe is talking about `pyvenv` instead of `venv`.
The entire subsection on virtual environments from Python deprecated section is quoted below.

> The `pyvenv` script has been deprecated in favour of `python3 -m venv`. This prevents confusion as to what Python interpreter `pyvenv` is connected to and thus what Python interpreter will be used by the virtual environment.
